
all :
	$(MAKE) -C ex00
	$(MAKE) -C ex01
	$(MAKE) -C ex02
	$(MAKE) -C ex03

run :
	$(MAKE) -C ex00 run
	$(MAKE) -C ex01 run
	$(MAKE) -C ex02 run
	$(MAKE) -C ex03 run

re :
	$(MAKE) -C ex00 re
	$(MAKE) -C ex01 re
	$(MAKE) -C ex02 re
	$(MAKE) -C ex03 re

clean :
	$(MAKE) -C ex00 fclean
	$(MAKE) -C ex01 fclean
	$(MAKE) -C ex02 fclean
	$(MAKE) -C ex03 fclean